name: Testing Workflow Variables

on:
  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest

    env:
      Greeting: Hello

    steps:
      - name: Say Hello
        env:
          First_Name: Vishal

        run: echo "$Greeting $First_Name is using $cloud"
